name: "CreeperRecover"
version: "1.2.1"
main: "de.rafael.plugins.creeper.recover.CreeperRecover"
api-version: "26.2"
description: "Silently restores Creeper damage in configured worlds"
author: "HttpRafa"
